#!/bin/sh

# NOTE:  If you are using cygwin on Windows, the colons in the CLASSPATH 
#        should be replaced with semi-colons
CLASSPATH=".;../core;../lib/messagebundles/;../lib/jars/collections.jar;../lib/jars/xerces.jar;../lib/jars/jl011.jar;../lib/jars/themes.jar;../lib/jars/logicrypto.jar;../lib/jars/mp3sp14.jar;../lib/jars/commons-httpclient.jar;../lib/jars/commons-logging.jar;../lib/jars/i18n.jar;../lib/jars/icu4j.jar;../lib/jars/ProgressTabs.jar;lib/jars/jmdns.jar;../gui;../core"

export CLASSPATH
PATH=$PATH:../lib/native
export PATH

java -Djava.util.logging.config.file=jdk14.logging.properties com.limegroup.gnutella.gui.Main
