#!/bin/sh

CLASSPATH=.:../core:../lib/messagebundles/:../lib/jars/collections.jar:\
../lib/jars/xerces.jar:../lib/jars/jl011.jar:../lib/jars/themes.jar:\
../lib/jars/logicrypto.jar:../lib/jars/mp3sp14.jar:\
../lib/jars/commons-httpclient.jar:../lib/jars/commons-logging.jar:\
../lib/jars/i18n.jar:../lib/jars/icu4j.jar:../lib/jars/ProgressTabs.jar:\
/System/Library/Java:\
lib/jars/jmdns.jar:../gui:../core

export CLASSPATH

java -Djava.library.path=../lib/native \
     -Djava.util.logging.config.file=jdk14.logging.properties \
     com.limegroup.gnutella.gui.Main
